MAX_HEADER_SCAN_ROWS = 15
TOP_K_COUNT = 10
TOP_K_MIN = 1

COLUMN_NAME = "姓名"
COLUMN_STUDENT_ID = "学号"
COLUMN_STUDENT_REGISTRATION_ID = "学籍号"
COLUMN_MATCH_KEY = "匹配主键"
COLUMN_CLASS_NAME = "班级"
COLUMN_POSITION = "排名"

SUBJECT_TOTAL_SCORE = "总分"
TOTAL_SUBJECT_ALIASES = {"总分", "总成绩", "语数外", "总计"}
SUBJECT_ALIASES = {"语数外": SUBJECT_TOTAL_SCORE}

METRIC_SCORE = "分数"
METRIC_YEAR_RANK = "年级排名"
METRIC_CLASS_RANK = "班级排名"
METRIC_RANK_CHANGE = "名次变化"
METRIC_CHANGE_DESCRIPTION = "变化描述"

SCORE_KEYWORDS = {"分数", "成绩", "得分"}
YEAR_RANK_KEYWORDS = {"年级名次", "年名次", "年级排名", "年排", "年级位次"}
CLASS_RANK_KEYWORDS = {"班名次", "班级名次", "班级排名", "班排"}

MAIN_HEADER_STOP_WORDS = {"", "nan", "none"}
EMPTY_VALUE_MARKERS = {"", "nan", "none"}

SEMESTER_FIRST = "第一学期"
SEMESTER_SECOND = "第二学期"

TOP_TYPE_IMPROVE = "进步TOP10"
TOP_TYPE_REGRESS = "退步TOP10"

SHEET_NAME_COMPARISON = "sheet1"
SHEET_NAME_TOP = "sheet2"

OUTPUT_COLUMN_INDICATOR = "指标"
OUTPUT_COLUMN_TYPE = "类型"

FREEZE_PANES_ANCHOR = "A2"
MIN_COLUMN_WIDTH = 12
MAX_COLUMN_WIDTH = 36
COLUMN_PADDING_WIDTH = 2
